@baseUrl = http://192.168.56.1:4567/

POST {{baseUrl}}suscripcion/crear_suscripcion
  content-type: application/json
  
  {
  "usuario_id": 1,
  "tipo_suscripcion": 1,
  "metodo_pago": "Tarjeta de Crédito",
  "productos": [
    {
      "id_producto": 1,
      "cantidad": 2
    },
    {
      "id_producto": 2,
      "cantidad": 1
    }
  ],
  "direccion": {
    "departamento": "Lima",
    "distrito": "Miraflores",
    "direccion": "Av. Pardo y Aliaga 1234",
    "numero": "456"
  }
}